Homework 25
NET16-Homeworks/Homework_Module25 pull request #2
Opened 2022-10-17 17:25 UTC by BFipe

Навернул полную тарелку LINQ

2022-10-23 11:17 UTC, im-kborovik requested changes

2022-10-23 11:17 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Job.cs
> +    enum JobSex
вынеси в отдельный файл и сделай общим для job и person

2022-10-23 11:17 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Person.cs
> +        public string? Email { get; set; }
какой смысл им всем указывать nullable тип? это итак строки.

2022-10-23 11:17 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                .Where(q => person.JobPreferances == null || q.Preferances.Intersect(person.JobPreferances) != null)
linq запросы никогда не возвращают null, кроме OrDefault методов. тут нужно просто проверить не пустая ли выборка.

2022-10-23 11:17 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +            }
вот с этим я в корне не согласен.  хорошо, что мои требования совпали по поиску, но они могли и не совпасть. создай отдельную реализацию для этого.

2022-10-27 19:56 UTC, im-kborovik requested changes

2022-10-27 19:56 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Person.cs
> +        public string Email { get { return email ?? "Not declared"; } set { email = value; } }
`{ return firstName ?? "John"; }` - а это зачем? всё ещё не понимаю логики.

2022-10-27 19:56 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferances { get; set; }
nullable листы? это что-то новое. лист итак nullable. зачем ему дописывать знак вопроса - не понимаю.

2022-10-27 19:56 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                .Where(q => person.JobPreferances == null || q.Preferances.Intersect(person.JobPreferances) != null)
всё ещё висит коммент

2022-10-28 06:26 UTC, BFipe commented on Homework_Module25/Homework_Module25/Person.cs
> +        public string Email { get { return email ?? "Not declared"; } set { email = value; } }
просто не хотелось, чтобы пустые значения висели, а то самому лень дописывать. Если это проблема, то удалю на следующем пуле

2022-10-28 08:44 UTC, BFipe commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferances { get; set; }
бесило зеленое подчеркивание)))

2022-11-13 11:02 UTC, im-kborovik approved these changes

2022-11-13 11:02 UTC, closed without merging