HW25 completed
NET16-Homeworks/Homework_Module25 pull request #3
Opened 2022-10-23 12:54 UTC by kricobelka

Есть неск моментов:
не выводит на консоль информацию в 1 и 2 методе, хоть джобы и персоны сопоставлены + есть тустринг

зеленым указаны комментарии

2022-10-27 19:41 UTC, im-kborovik requested changes

2022-10-27 19:41 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Job.cs
> +        public Nullable<int> EndAge { get; set; }
nullable<T> это уже давно устаревшая запись. используй `T?` например `int?`

2022-10-27 19:41 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferences { get; set; }
nullable лист? что-то новое. коллекцию всегда нужно инициализировать

2022-10-27 19:41 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                    .Where(q => q.Preferences.Intersect(person.JobPreferences) != null)
Intersect вовзращает коллекцию в любом случае

2022-10-27 19:41 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +            int age = DateTime.Now.Year - person.BirthDate.Year;
Зачем тебе эта запись?

2022-10-27 19:41 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                .Where(q => age >= job.StartAge && age <= job.EndAge)
так не будет работать. нужно использовать age человека на конкретной итерации linq:  q.Age

2022-10-30 19:44 UTC, kricobelka commented on Homework_Module25/Homework_Module25/Job.cs
> +        public Nullable<int> EndAge { get; set; }
ок, хотела двумя способами написать)

2022-10-30 19:44 UTC, kricobelka commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferences { get; set; }
done

2022-10-30 21:01 UTC, kricobelka commented on Homework_Module25/Homework_Module25/Searcher.cs
> +            int age = DateTime.Now.Year - person.BirthDate.Year;
fixed

2022-10-30 21:02 UTC, kricobelka commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                .Where(q => age >= job.StartAge && age <= job.EndAge)
создала метод, изменила на q.Age()

2022-10-30 21:13 UTC, kricobelka commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                    .Where(q => q.Preferences.Intersect(person.JobPreferences) != null)
fixed

2022-11-06 19:07 UTC, im-kborovik approved these changes

2022-11-06 19:08 UTC, closed without merging