Added Homework 25 LINQ
NET16-Homeworks/Homework_Module25 pull request #4
Opened 2022-10-25 10:16 UTC by VladPulyak

Немного заморочился с выводом на консоль

2022-10-27 20:12 UTC, im-kborovik requested changes

2022-10-27 20:12 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferances { get; set; }
в  nullable листе нет смысла, это ссылочный тип, он по умолчанию nullable.

2022-10-27 20:12 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                        return false;
Почитай про метод Intersect :) я о нём уже рассказывал на лекции.

2022-10-27 20:12 UTC, im-kborovik commented on Homework_Module25/Homework_Module25/Searcher.cs
> +        }
Это можно сделать красивее через join :)

2022-10-27 21:01 UTC, VladPulyak commented on Homework_Module25/Homework_Module25/Person.cs
> +        public List<string>? LocationPreferances { get; set; }
Исправил

2022-10-27 21:01 UTC, VladPulyak commented on Homework_Module25/Homework_Module25/Searcher.cs
> +                        return false;
Исправил

2022-10-27 21:01 UTC, VladPulyak commented on Homework_Module25/Homework_Module25/Searcher.cs
> +        }
Исправил

2022-11-06 19:09 UTC, im-kborovik approved these changes

2022-11-06 19:09 UTC, closed without merging